### ISSUE TITLE
TypesenseTimeField: Django TimeField has no timestamp

### ISSUE THREAD

**Issue by KengoWada** [Siege-Software/django-typesense#45]
## Description
Django `TimeField` does not have timestamp

From the Django documentation, [TimeField](https://docs.djangoproject.com/en/4.2/ref/models/fields/#timefield) states

> A time, represented in Python by a `datetime.time` instance.

I think the best representation for `TypesenseTimeField` would be `string`

**Comment by EricOuma** [comment]
Sorting strings is an expensive operation so it has to be an integer
This is handled internally by `TypesenseDateTimeFieldBase`

**Comment by KengoWada** [comment]
> Sorting strings is an expensive operation so it has to be an integer This is handled internally by `TypesenseDateTimeFieldBase`

This means that a date has to added to the time to convert it to a timestamp because `datetime.time` can not be converted to timestamp directly.

WDYT

**Comment by EricOuma** [comment]
This is handled internally by `TypesenseDateTimeFieldBase`

**Comment by KengoWada** [comment]
```py
class SongCollection(TypesenseCollection):
    ...
    release_time = fields.TypesenseTimeField()

class Song(TypesenseModelMixin):
    ...
    release_time = models.TimeField()
```

The above set up returns `TypeError: Field 'None' expected a number but got 09:54:34.`

**Comment by EricOuma** [comment]
I'll be releasing a new version today. See if you still get the error on it once I release.

**Comment by KengoWada** [comment]
> I'll be releasing a new version today. See if you still get the error on it once I release.

The new changes fix this. I'll be closing this.
