### ISSUE TITLE
Update utils file.

### ISSUE THREAD

**Issue by KengoWada** [Siege-Software/django-typesense#52]
## Suggestions
- Throw more specific exceptions other than `Exception` as it is best practice to not catch general exceptions.
- Format the file according to the black standard.

**Comment by EricOuma** [comment]
Did you install pre-commit as described in the contributing doc?
Formatting should be done automatically when you make commits. It's also done in the CI.

**Comment by KengoWada** [comment]
@EricOuma noted. So should I proceed with the changing of `Exceptions` to more appropriate exceptions?

**Comment by EricOuma** [comment]
okay.

**Comment by KengoWada** [comment]
Hey @EricOuma please assign this to me.
