### ISSUE TITLE
ValueError (Delete)

### ISSUE THREAD

**Issue by Ysnz** [Siege-Software/django-typesense#72]
## Description

When attempting to delete an object in the admin interface, an internal server error occurs. The error is specifically related to the attempt to convert a UUID ('90b608d0-1684-4b5e-adf3-fb5c0c21ca96') to an integer during the deletion process.

### How To Reproduce

1. Go to the admin interface.
2. Navigate to the page where you can delete an object.
3. Attempt to delete an object with the UUID '90b608d0-1684-4b5e-adf3-fb5c0c21ca96'.
4. Observe the internal server error.

### Expected behavior

The deletion process should occur without errors, and the object with the provided UUID should be deleted successfully.

**Additional context**

The issue is related to the attempt to convert UUIDs to integers during the deletion process, resulting in a ValueError.

### Screenshots

![image](https://github.com/Siege-Software/django-typesense/assets/55712458/73457c70-5a5e-4885-a206-fa0bc93b72c7)

**Comment by KengoWada** [comment]
Hey @Ysnz thanks for reporting the bug. I'm going to try and replicate it to confirm the bug.

**Comment by KengoWada** [comment]
Hey @EricOuma I can confirm the bug that has been reported. I will start working on a fix. Please assign this to me and mark it as a bug.

**Comment by EricOuma** [comment]
@KengoWada Let me know how you plan to approach the problem before you make a PR.

**Comment by KengoWada** [comment]
@EricOuma this is my current solution
```diff
- delete_params = {"filter_by": f"id:{[int(obj['id']) for obj in self.data]}"}

+ object_ids = []
+ for obj in self.data:
+     try:
+         object_id = int(obj["id"])
+     except ValueError:
+         object_id = str(obj["id"])
+     object_ids.append(object_id)
+
+ if all(isinstance(id_, int) for id_ in object_ids):
+     filter_by = f"id:{object_ids}"
+ else:
+     filter_by = f"id: {object_ids}".replace("'", "")
+
+ delete_params = {"filter_by": filter_by}
```
WDYT

**Comment by EricOuma** [comment]
What happens if you don't convert it to an integer at all; just using the
id as is. I don't think typesense is aware that its an integer.

**Comment by KengoWada** [comment]
@EricOuma Yeah, that's the way to go. You need to remove the single quotes that Python adds to strings. According to Typesense `filter_by` [formatting rules](https://typesense.org/docs/0.25.2/api/search.html#query-parameters).

```diff
- delete_params = {"filter_by": f"id:{[int(obj['id']) for obj in self.data]}"}
+ delete_params = {"filter_by": f"id: {[obj['id'] for obj in self.data]}".replace("'", "")}
```
