### ISSUE TITLE
The README file is missing an example of TYPESENSE settings dictionary

### ISSUE THREAD

**Issue by archatas** [Siege-Software/django-typesense#94]
## Description

There is no mentioning and example of `settings.TYPESENSE` and one needs to inspect the source to figure out what to set there.

### How To Reproduce

Try to set up a project with __django-typesense__.

### Expected behavior

After following the examples in the README, I expect to have a sample project running.

So here's what I expect to be added to the README:

```python
TYPESENSE = {
    "api_key": "xyz",
    "nodes": [{"host": "0.0.0.0", "port": "8108", "protocol": "http"}],
    "connection_timeout_seconds": 2
}
```

### Environment Details

- OS: MacOS Sonoma 14.7

- Versions:

  - Python: 3.10
  - Django: 5.1
  - django_typesense: 0.1.3

**Comment by EricOuma** [comment]
@KengoWada Are you able to work on this?

**Comment by KengoWada** [comment]
@EricOuma I'll start on this.
